[versions]
# Project Versions
javaVersion = "21"
compileSdk = "35"
targetSdk = "35"
minSdk = "24"
versionCode = "1"
versionName = "0.0.1.0"

activityCompose = "1.10.1"
agp = "8.12.0"
coil = "3.3.0"
composeBom = "2025.07.00"
coreKtx = "1.16.0"
coroutines = "1.10.2"
dagger-hilt = "2.57"
hilt = "1.2.0"
jetbrainsKotlinJvm = "2.1.0"
kotlin = "2.1.0"
kotlinxSerializationJson = "1.9.0"
ksp = "2.1.0-1.0.29"
lifecycleRuntimeKtx = "2.9.2"
navigationCompose = "2.9.3"
okhttp = "5.1.0"
retrofit = "2.11.0"
room = "2.7.2"
uiTextGoogleFonts = "1.8.3"

# Testing Versions
androidJunit = "1.3.0"
compose-test = "1.8.3"
espressoCore = "3.7.0"
junit = "4.13.2"
junit5 = "5.11.3"
kluent = "1.73"
kotest = "5.9.1"
kover = "0.9.1"
mockk = "1.13.13"
paparazzi = "1.3.5"
splashscreen = "1.0.1"
turbine = "1.2.1"
appcompat = "1.7.1"
material = "1.12.0"
storage = "1.6.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

# Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
androidx-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }

# Coil
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }

# Hilt
dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger-hilt" }
dagger-hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "dagger-hilt" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger-hilt" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt" }

# Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

# Encrypted Shared Prefs
encrypted-shared-prefs = { group = "androidx.security", name = "security-crypto", version = "1.1.0-alpha03" }

# Retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "retrofit" }

# Room
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }

# Startup Initializer
androidx-startup = { module = "androidx.startup:startup-runtime", version = "1.2.0" }

# Logging interceptor
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version = "34.1.0" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth-ktx", version = "23.2.1" }
google-identity = { group = "com.google.android.gms", name = "play-services-auth", version = "21.4.0" }
firebase-remote-config = { module = "com.google.firebase:firebase-config" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidJunit" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose-test" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
paparazzi = { group = "app.cash.paparazzi", name = "paparazzi", version.ref = "paparazzi" }

junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit5" }
junit-jupiter-vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junit5" }

kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

kluent = { group = "org.amshove.kluent", name = "kluent", version.ref = "kluent" }
kluent-android = { group = "org.amshove.kluent", name = "kluent-android", version.ref = "kluent" }
kotest = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

# Build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
androidx-storage = { group = "androidx.test.services", name = "storage", version.ref = "storage" }

[bundles]
compose = [
    "androidx-activity-compose",
    "androidx-compose-material3",
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling-preview",
]

compose-debug = [
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-test-manifest",
]

coil = [
    "coil-compose",
    "coil-network",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
crashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.2" }
google-services = { id = "com.google.gms.google-services", version = "4.4.4" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
room = { id = "androidx.room", version.ref = "room" }

# Quality Plugins
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "13.0.0" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.8" }

# Custom Plugins
convention-android-application = { id = "com.asensiodev.santoro.buildlogic.convention.android-application" }
convention-android-application-compose = { id = "com.asensiodev.santoro.buildlogic.convention.android-application-compose" }
convention-android-library = { id = "com.asensiodev.santoro.buildlogic.convention.android-library" }
convention-android-library-compose = { id = "com.asensiodev.santoro.buildlogic.convention.android-library-compose" }
convention-android-feature = { id = "com.asensiodev.santoro.buildlogic.convention.android-feature" }
convention-jvm-library = { id = "com.asensiodev.santoro.buildlogic.convention.jvm-library" }
convention-android-hilt = { id = "com.asensiodev.santoro.buildlogic.convention.android-hilt" }
convention-jvm-hilt = { id = "com.asensiodev.santoro.buildlogic.convention.jvm-hilt" }
convention-android-test = { id = "com.asensiodev.santoro.buildlogic.convention.android-test" }
convention-jvm-test = { id = "com.asensiodev.santoro.buildlogic.convention.jvm-test" }
convention-paparazzi = { id = "com.asensiodev.santoro.buildlogic.convention.paparazzi" }
convention-android-room = { id = "com.asensiodev.santoro.buildlogic.convention.android-room" }
